// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALqBnVC6FYTclbvmXN1tq5IxBh8QuVWLg',
    appId: '1:355715477232:web:4871a04c19eb9dd2369c35',
    messagingSenderId: '355715477232',
    projectId: 'raahenijaat',
    authDomain: 'raahenijaat.firebaseapp.com',
    databaseURL: 'https://raahenijaat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raahenijaat.appspot.com',
    measurementId: 'G-LEBTXNH1CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6NTGjSAn5RSWyfiGQBtTPHVIdCdNzKg8',
    appId: '1:355715477232:android:71affac1097c4fe5369c35',
    messagingSenderId: '355715477232',
    projectId: 'raahenijaat',
    databaseURL: 'https://raahenijaat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raahenijaat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv85TjvOwp4dDDMUURGMM2NOs5BQNosYs',
    appId: '1:355715477232:ios:960580c0d08c0bc3369c35',
    messagingSenderId: '355715477232',
    projectId: 'raahenijaat',
    databaseURL: 'https://raahenijaat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raahenijaat.appspot.com',
    androidClientId: '355715477232-4ncpqopmj7mhs4ruj0vao96ujktn4426.apps.googleusercontent.com',
    iosClientId: '355715477232-l1i5afl9ublc9caa81s7qr90ocnclrr9.apps.googleusercontent.com',
    iosBundleId: 'com.raahenijaat.raahENijaat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv85TjvOwp4dDDMUURGMM2NOs5BQNosYs',
    appId: '1:355715477232:ios:960580c0d08c0bc3369c35',
    messagingSenderId: '355715477232',
    projectId: 'raahenijaat',
    databaseURL: 'https://raahenijaat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raahenijaat.appspot.com',
    androidClientId: '355715477232-4ncpqopmj7mhs4ruj0vao96ujktn4426.apps.googleusercontent.com',
    iosClientId: '355715477232-l1i5afl9ublc9caa81s7qr90ocnclrr9.apps.googleusercontent.com',
    iosBundleId: 'com.raahenijaat.raahENijaat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALqBnVC6FYTclbvmXN1tq5IxBh8QuVWLg',
    appId: '1:355715477232:web:a56143b89fa1ead4369c35',
    messagingSenderId: '355715477232',
    projectId: 'raahenijaat',
    authDomain: 'raahenijaat.firebaseapp.com',
    databaseURL: 'https://raahenijaat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raahenijaat.appspot.com',
    measurementId: 'G-7NVXVDQ289',
  );
}
